services:
  portfolio:
    image: ghcr.io/krbob/portfolio:main
    ports:
      - "7777:7777"
    depends_on:
      - portfolio-backend
    environment:
      - BACKEND_URL=http://portfolio-backend:7776
    restart: unless-stopped

  portfolio-backend:
    image: ghcr.io/krbob/portfolio-backend:main
    restart: unless-stopped