name: CI Build Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build
        run: chmod +x gradlew && ./gradlew assemble

      - name: Test
        run: ./gradlew test

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: portfolio
          path: build/libs/*.jar